# Generated by Django 3.1.3 on 2021-07-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='nswer',
        ),
    ]
