# Generated by Django 3.1.3 on 2021-07-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_auto_20210702_0343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nswer',
            new_name='Answer',
        ),
    ]
